


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package mac0_s_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter mac0_s_vip_VIP_INTERFACE_MODE     = 0;
      parameter mac0_s_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter mac0_s_vip_VIP_DATA_WIDTH         = 512;
      parameter mac0_s_vip_VIP_ID_WIDTH           = 0;
      parameter mac0_s_vip_VIP_DEST_WIDTH         = 0;
      parameter mac0_s_vip_VIP_USER_WIDTH         = 0;
      parameter mac0_s_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter mac0_s_vip_VIP_HAS_TREADY         = 1;
      parameter mac0_s_vip_VIP_HAS_TSTRB          = 0;
      parameter mac0_s_vip_VIP_HAS_TKEEP          = 1;
      parameter mac0_s_vip_VIP_HAS_TLAST          = 1;
      parameter mac0_s_vip_VIP_HAS_ACLKEN         = 0;
      parameter mac0_s_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(mac0_s_vip_VIP_SIGNAL_SET, 
                        mac0_s_vip_VIP_DEST_WIDTH,
                        mac0_s_vip_VIP_DATA_WIDTH,
                        mac0_s_vip_VIP_ID_WIDTH,
                        mac0_s_vip_VIP_USER_WIDTH, 
                        mac0_s_vip_VIP_USER_BITS_PER_BYTE,
                        mac0_s_vip_VIP_HAS_ARESETN) mac0_s_vip_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      mac0_s_vip_mst_t  mac0_s_vip_mst;
//      initial begin : START_mac0_s_vip_MASTER
//        mac0_s_vip_mst = new("mac0_s_vip_mst", `mac0_s_vip_PATH_TO_INTERFACE);
//        mac0_s_vip_mst.start_master();
//      end



endpackage : mac0_s_vip_pkg
