


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package mac0_m_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter mac0_m_vip_VIP_INTERFACE_MODE     = 2;
      parameter mac0_m_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter mac0_m_vip_VIP_DATA_WIDTH         = 512;
      parameter mac0_m_vip_VIP_ID_WIDTH           = 0;
      parameter mac0_m_vip_VIP_DEST_WIDTH         = 0;
      parameter mac0_m_vip_VIP_USER_WIDTH         = 0;
      parameter mac0_m_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter mac0_m_vip_VIP_HAS_TREADY         = 1;
      parameter mac0_m_vip_VIP_HAS_TSTRB          = 0;
      parameter mac0_m_vip_VIP_HAS_TKEEP          = 1;
      parameter mac0_m_vip_VIP_HAS_TLAST          = 1;
      parameter mac0_m_vip_VIP_HAS_ACLKEN         = 0;
      parameter mac0_m_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(mac0_m_vip_VIP_SIGNAL_SET, 
                        mac0_m_vip_VIP_DEST_WIDTH,
                        mac0_m_vip_VIP_DATA_WIDTH,
                        mac0_m_vip_VIP_ID_WIDTH,
                        mac0_m_vip_VIP_USER_WIDTH, 
                        mac0_m_vip_VIP_USER_BITS_PER_BYTE,
                        mac0_m_vip_VIP_HAS_ARESETN) mac0_m_vip_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      mac0_m_vip_slv_t  mac0_m_vip_slv;
//      initial begin : START_mac0_m_vip_SLAVE
//        mac0_m_vip_slv = new("mac0_m_vip_slv", `mac0_m_vip_PATH_TO_INTERFACE);
//        mac0_m_vip_slv.start_slave();
//      end

endpackage : mac0_m_vip_pkg
