// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rtl_kernel_wizard_0_rtl_kernel_wizard_0,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=12433,HLS_SYN_TPT=none,HLS_SYN_MEM=62,HLS_SYN_DSP=0,HLS_SYN_FF=3427,HLS_SYN_LUT=3355,HLS_VERSION=2020_2}" *)

module rtl_kernel_wizard_0 (
        ap_clk,
        ap_rst_n,
        m_axi_A_AWVALID,
        m_axi_A_AWREADY,
        m_axi_A_AWADDR,
        m_axi_A_AWID,
        m_axi_A_AWLEN,
        m_axi_A_AWSIZE,
        m_axi_A_AWBURST,
        m_axi_A_AWLOCK,
        m_axi_A_AWCACHE,
        m_axi_A_AWPROT,
        m_axi_A_AWQOS,
        m_axi_A_AWREGION,
        m_axi_A_AWUSER,
        m_axi_A_WVALID,
        m_axi_A_WREADY,
        m_axi_A_WDATA,
        m_axi_A_WSTRB,
        m_axi_A_WLAST,
        m_axi_A_WID,
        m_axi_A_WUSER,
        m_axi_A_ARVALID,
        m_axi_A_ARREADY,
        m_axi_A_ARADDR,
        m_axi_A_ARID,
        m_axi_A_ARLEN,
        m_axi_A_ARSIZE,
        m_axi_A_ARBURST,
        m_axi_A_ARLOCK,
        m_axi_A_ARCACHE,
        m_axi_A_ARPROT,
        m_axi_A_ARQOS,
        m_axi_A_ARREGION,
        m_axi_A_ARUSER,
        m_axi_A_RVALID,
        m_axi_A_RREADY,
        m_axi_A_RDATA,
        m_axi_A_RLAST,
        m_axi_A_RID,
        m_axi_A_RUSER,
        m_axi_A_RRESP,
        m_axi_A_BVALID,
        m_axi_A_BREADY,
        m_axi_A_BRESP,
        m_axi_A_BID,
        m_axi_A_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 144'd1;
parameter    ap_ST_fsm_state2 = 144'd2;
parameter    ap_ST_fsm_state3 = 144'd4;
parameter    ap_ST_fsm_state4 = 144'd8;
parameter    ap_ST_fsm_state5 = 144'd16;
parameter    ap_ST_fsm_state6 = 144'd32;
parameter    ap_ST_fsm_state7 = 144'd64;
parameter    ap_ST_fsm_state8 = 144'd128;
parameter    ap_ST_fsm_state9 = 144'd256;
parameter    ap_ST_fsm_state10 = 144'd512;
parameter    ap_ST_fsm_state11 = 144'd1024;
parameter    ap_ST_fsm_state12 = 144'd2048;
parameter    ap_ST_fsm_state13 = 144'd4096;
parameter    ap_ST_fsm_state14 = 144'd8192;
parameter    ap_ST_fsm_state15 = 144'd16384;
parameter    ap_ST_fsm_state16 = 144'd32768;
parameter    ap_ST_fsm_state17 = 144'd65536;
parameter    ap_ST_fsm_state18 = 144'd131072;
parameter    ap_ST_fsm_state19 = 144'd262144;
parameter    ap_ST_fsm_state20 = 144'd524288;
parameter    ap_ST_fsm_state21 = 144'd1048576;
parameter    ap_ST_fsm_state22 = 144'd2097152;
parameter    ap_ST_fsm_state23 = 144'd4194304;
parameter    ap_ST_fsm_state24 = 144'd8388608;
parameter    ap_ST_fsm_state25 = 144'd16777216;
parameter    ap_ST_fsm_state26 = 144'd33554432;
parameter    ap_ST_fsm_state27 = 144'd67108864;
parameter    ap_ST_fsm_state28 = 144'd134217728;
parameter    ap_ST_fsm_state29 = 144'd268435456;
parameter    ap_ST_fsm_state30 = 144'd536870912;
parameter    ap_ST_fsm_state31 = 144'd1073741824;
parameter    ap_ST_fsm_state32 = 144'd2147483648;
parameter    ap_ST_fsm_state33 = 144'd4294967296;
parameter    ap_ST_fsm_state34 = 144'd8589934592;
parameter    ap_ST_fsm_state35 = 144'd17179869184;
parameter    ap_ST_fsm_state36 = 144'd34359738368;
parameter    ap_ST_fsm_state37 = 144'd68719476736;
parameter    ap_ST_fsm_state38 = 144'd137438953472;
parameter    ap_ST_fsm_state39 = 144'd274877906944;
parameter    ap_ST_fsm_state40 = 144'd549755813888;
parameter    ap_ST_fsm_state41 = 144'd1099511627776;
parameter    ap_ST_fsm_state42 = 144'd2199023255552;
parameter    ap_ST_fsm_state43 = 144'd4398046511104;
parameter    ap_ST_fsm_state44 = 144'd8796093022208;
parameter    ap_ST_fsm_state45 = 144'd17592186044416;
parameter    ap_ST_fsm_state46 = 144'd35184372088832;
parameter    ap_ST_fsm_state47 = 144'd70368744177664;
parameter    ap_ST_fsm_state48 = 144'd140737488355328;
parameter    ap_ST_fsm_state49 = 144'd281474976710656;
parameter    ap_ST_fsm_state50 = 144'd562949953421312;
parameter    ap_ST_fsm_state51 = 144'd1125899906842624;
parameter    ap_ST_fsm_state52 = 144'd2251799813685248;
parameter    ap_ST_fsm_state53 = 144'd4503599627370496;
parameter    ap_ST_fsm_state54 = 144'd9007199254740992;
parameter    ap_ST_fsm_state55 = 144'd18014398509481984;
parameter    ap_ST_fsm_state56 = 144'd36028797018963968;
parameter    ap_ST_fsm_state57 = 144'd72057594037927936;
parameter    ap_ST_fsm_state58 = 144'd144115188075855872;
parameter    ap_ST_fsm_state59 = 144'd288230376151711744;
parameter    ap_ST_fsm_state60 = 144'd576460752303423488;
parameter    ap_ST_fsm_state61 = 144'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 144'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 144'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 144'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 144'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 144'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 144'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 144'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 144'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 144'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 144'd1180591620717411303424;
parameter    ap_ST_fsm_pp0_stage0 = 144'd2361183241434822606848;
parameter    ap_ST_fsm_state75 = 144'd4722366482869645213696;
parameter    ap_ST_fsm_pp1_stage0 = 144'd9444732965739290427392;
parameter    ap_ST_fsm_state78 = 144'd18889465931478580854784;
parameter    ap_ST_fsm_pp2_stage0 = 144'd37778931862957161709568;
parameter    ap_ST_fsm_state82 = 144'd75557863725914323419136;
parameter    ap_ST_fsm_state83 = 144'd151115727451828646838272;
parameter    ap_ST_fsm_state84 = 144'd302231454903657293676544;
parameter    ap_ST_fsm_state85 = 144'd604462909807314587353088;
parameter    ap_ST_fsm_state86 = 144'd1208925819614629174706176;
parameter    ap_ST_fsm_state87 = 144'd2417851639229258349412352;
parameter    ap_ST_fsm_state88 = 144'd4835703278458516698824704;
parameter    ap_ST_fsm_state89 = 144'd9671406556917033397649408;
parameter    ap_ST_fsm_state90 = 144'd19342813113834066795298816;
parameter    ap_ST_fsm_state91 = 144'd38685626227668133590597632;
parameter    ap_ST_fsm_state92 = 144'd77371252455336267181195264;
parameter    ap_ST_fsm_state93 = 144'd154742504910672534362390528;
parameter    ap_ST_fsm_state94 = 144'd309485009821345068724781056;
parameter    ap_ST_fsm_state95 = 144'd618970019642690137449562112;
parameter    ap_ST_fsm_state96 = 144'd1237940039285380274899124224;
parameter    ap_ST_fsm_state97 = 144'd2475880078570760549798248448;
parameter    ap_ST_fsm_state98 = 144'd4951760157141521099596496896;
parameter    ap_ST_fsm_state99 = 144'd9903520314283042199192993792;
parameter    ap_ST_fsm_state100 = 144'd19807040628566084398385987584;
parameter    ap_ST_fsm_state101 = 144'd39614081257132168796771975168;
parameter    ap_ST_fsm_state102 = 144'd79228162514264337593543950336;
parameter    ap_ST_fsm_state103 = 144'd158456325028528675187087900672;
parameter    ap_ST_fsm_state104 = 144'd316912650057057350374175801344;
parameter    ap_ST_fsm_state105 = 144'd633825300114114700748351602688;
parameter    ap_ST_fsm_state106 = 144'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state107 = 144'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state108 = 144'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state109 = 144'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state110 = 144'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state111 = 144'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state112 = 144'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state113 = 144'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state114 = 144'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state115 = 144'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state116 = 144'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state117 = 144'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state118 = 144'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state119 = 144'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state120 = 144'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state121 = 144'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state122 = 144'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state123 = 144'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state124 = 144'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state125 = 144'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state126 = 144'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state127 = 144'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state128 = 144'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state129 = 144'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state130 = 144'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state131 = 144'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state132 = 144'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state133 = 144'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state134 = 144'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state135 = 144'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state136 = 144'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state137 = 144'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state138 = 144'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state139 = 144'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state140 = 144'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state141 = 144'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state142 = 144'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state143 = 144'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state144 = 144'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state145 = 144'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state146 = 144'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state147 = 144'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state148 = 144'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state149 = 144'd11150372599265311570767859136324180752990208;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_ID_WIDTH = 1;
parameter    C_M_AXI_A_ADDR_WIDTH = 64;
parameter    C_M_AXI_A_DATA_WIDTH = 512;
parameter    C_M_AXI_A_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_USER_VALUE = 0;
parameter    C_M_AXI_A_PROT_VALUE = 0;
parameter    C_M_AXI_A_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_A_AWVALID;
input   m_axi_A_AWREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_A_AWADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_A_AWID;
output  [7:0] m_axi_A_AWLEN;
output  [2:0] m_axi_A_AWSIZE;
output  [1:0] m_axi_A_AWBURST;
output  [1:0] m_axi_A_AWLOCK;
output  [3:0] m_axi_A_AWCACHE;
output  [2:0] m_axi_A_AWPROT;
output  [3:0] m_axi_A_AWQOS;
output  [3:0] m_axi_A_AWREGION;
output  [C_M_AXI_A_AWUSER_WIDTH - 1:0] m_axi_A_AWUSER;
output   m_axi_A_WVALID;
input   m_axi_A_WREADY;
output  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_A_WDATA;
output  [C_M_AXI_A_WSTRB_WIDTH - 1:0] m_axi_A_WSTRB;
output   m_axi_A_WLAST;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_A_WID;
output  [C_M_AXI_A_WUSER_WIDTH - 1:0] m_axi_A_WUSER;
output   m_axi_A_ARVALID;
input   m_axi_A_ARREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_A_ARADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_A_ARID;
output  [7:0] m_axi_A_ARLEN;
output  [2:0] m_axi_A_ARSIZE;
output  [1:0] m_axi_A_ARBURST;
output  [1:0] m_axi_A_ARLOCK;
output  [3:0] m_axi_A_ARCACHE;
output  [2:0] m_axi_A_ARPROT;
output  [3:0] m_axi_A_ARQOS;
output  [3:0] m_axi_A_ARREGION;
output  [C_M_AXI_A_ARUSER_WIDTH - 1:0] m_axi_A_ARUSER;
input   m_axi_A_RVALID;
output   m_axi_A_RREADY;
input  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_A_RDATA;
input   m_axi_A_RLAST;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_A_RID;
input  [C_M_AXI_A_RUSER_WIDTH - 1:0] m_axi_A_RUSER;
input  [1:0] m_axi_A_RRESP;
input   m_axi_A_BVALID;
output   m_axi_A_BREADY;
input  [1:0] m_axi_A_BRESP;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_A_BID;
input  [C_M_AXI_A_BUSER_WIDTH - 1:0] m_axi_A_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [143:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] scalar00;
wire   [63:0] axi00_ptr0;
reg    A_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    A_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond64_reg_420;
reg   [0:0] empty_25_reg_424;
reg    A_blk_n_AW;
wire    ap_CS_fsm_state78;
reg    A_blk_n_W;
reg    ap_enable_reg_pp2_iter2;
wire    ap_block_pp2_stage0;
reg   [0:0] empty_33_reg_471;
reg   [0:0] empty_33_reg_471_pp2_iter1_reg;
reg    A_blk_n_B;
wire    ap_CS_fsm_state149;
reg    A_AWVALID;
wire    A_AWREADY;
reg    A_WVALID;
wire    A_WREADY;
wire   [511:0] A_WDATA;
reg    A_ARVALID;
wire    A_ARREADY;
wire    A_RVALID;
reg    A_RREADY;
wire   [511:0] A_RDATA;
wire    A_RLAST;
wire   [0:0] A_RID;
wire   [0:0] A_RUSER;
wire   [1:0] A_RRESP;
wire    A_BVALID;
reg    A_BREADY;
wire   [1:0] A_BRESP;
wire   [0:0] A_BID;
wire   [0:0] A_BUSER;
reg   [12:0] loop_index4_reg_186;
reg   [12:0] loop_index4_reg_186_pp0_iter1_reg;
wire    ap_block_state72_pp0_stage0_iter0;
reg    ap_predicate_op246_read_state73;
reg    ap_block_state73_pp0_stage0_iter1;
wire    ap_block_state74_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [479:0] shiftreg9_reg_198;
reg   [12:0] i_reg_219;
reg   [12:0] loop_index_reg_230;
reg   [479:0] shiftreg_reg_241;
reg   [57:0] trunc_ln_reg_403;
reg   [63:0] A_addr_reg_408;
wire   [12:0] empty_22_fu_273_p2;
reg   [12:0] empty_22_reg_415;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond64_fu_279_p2;
reg   [0:0] exitcond64_reg_420_pp0_iter1_reg;
wire   [0:0] empty_25_fu_289_p2;
reg   [0:0] empty_25_reg_424_pp0_iter1_reg;
reg   [511:0] A_addr_read_reg_428;
reg    ap_enable_reg_pp0_iter2;
wire   [12:0] add_ln52_fu_320_p2;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state76_pp1_stage0_iter0;
wire    ap_block_state77_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln52_fu_326_p2;
reg   [0:0] icmp_ln52_reg_443;
wire   [63:0] i_cast_fu_332_p1;
reg   [63:0] i_cast_reg_447;
wire   [12:0] empty_30_fu_344_p2;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state79_pp2_stage0_iter0;
wire    ap_block_state80_pp2_stage0_iter1;
wire    ap_block_state81_pp2_stage0_iter2;
reg    ap_block_state81_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond2_fu_350_p2;
reg   [0:0] exitcond2_reg_462;
reg   [0:0] exitcond2_reg_462_pp2_iter1_reg;
wire   [0:0] empty_33_fu_365_p2;
wire   [31:0] A_output_buffer_q0;
reg   [31:0] A_output_buffer_load_reg_476;
reg    ap_enable_reg_pp2_iter1;
wire   [479:0] empty_34_fu_396_p3;
wire    ap_CS_fsm_state71;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state72;
wire    ap_CS_fsm_state75;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state76;
reg    ap_enable_reg_pp1_iter1;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state79;
reg   [12:0] A_input_buffer_address0;
reg    A_input_buffer_ce0;
reg    A_input_buffer_we0;
wire   [31:0] A_input_buffer_d0;
wire   [31:0] A_input_buffer_q0;
reg   [12:0] A_output_buffer_address0;
reg    A_output_buffer_ce0;
reg    A_output_buffer_we0;
wire   [31:0] A_output_buffer_d0;
reg   [12:0] ap_phi_mux_loop_index4_phi_fu_190_p4;
reg   [511:0] ap_phi_mux_empty_26_phi_fu_213_p4;
wire   [511:0] ap_phi_reg_pp0_iter2_empty_26_reg_210;
wire   [511:0] shiftreg9_cast_fu_295_p1;
wire   [63:0] loop_index4_cast2_fu_300_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] loop_index_cast3_fu_356_p1;
wire   [63:0] sext_ln49_fu_263_p1;
wire    ap_block_pp2_stage0_01001;
wire   [3:0] empty_24_fu_285_p1;
wire   [3:0] empty_32_fu_361_p1;
wire   [447:0] tmp_1_fu_379_p4;
wire   [479:0] tmp_2_fu_389_p3;
reg   [143:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 144'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

rtl_kernel_wizard_0_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .scalar00(scalar00),
    .axi00_ptr0(axi00_ptr0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rtl_kernel_wizard_0_A_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_A_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_CACHE_VALUE ))
A_m_axi_U(
    .AWVALID(m_axi_A_AWVALID),
    .AWREADY(m_axi_A_AWREADY),
    .AWADDR(m_axi_A_AWADDR),
    .AWID(m_axi_A_AWID),
    .AWLEN(m_axi_A_AWLEN),
    .AWSIZE(m_axi_A_AWSIZE),
    .AWBURST(m_axi_A_AWBURST),
    .AWLOCK(m_axi_A_AWLOCK),
    .AWCACHE(m_axi_A_AWCACHE),
    .AWPROT(m_axi_A_AWPROT),
    .AWQOS(m_axi_A_AWQOS),
    .AWREGION(m_axi_A_AWREGION),
    .AWUSER(m_axi_A_AWUSER),
    .WVALID(m_axi_A_WVALID),
    .WREADY(m_axi_A_WREADY),
    .WDATA(m_axi_A_WDATA),
    .WSTRB(m_axi_A_WSTRB),
    .WLAST(m_axi_A_WLAST),
    .WID(m_axi_A_WID),
    .WUSER(m_axi_A_WUSER),
    .ARVALID(m_axi_A_ARVALID),
    .ARREADY(m_axi_A_ARREADY),
    .ARADDR(m_axi_A_ARADDR),
    .ARID(m_axi_A_ARID),
    .ARLEN(m_axi_A_ARLEN),
    .ARSIZE(m_axi_A_ARSIZE),
    .ARBURST(m_axi_A_ARBURST),
    .ARLOCK(m_axi_A_ARLOCK),
    .ARCACHE(m_axi_A_ARCACHE),
    .ARPROT(m_axi_A_ARPROT),
    .ARQOS(m_axi_A_ARQOS),
    .ARREGION(m_axi_A_ARREGION),
    .ARUSER(m_axi_A_ARUSER),
    .RVALID(m_axi_A_RVALID),
    .RREADY(m_axi_A_RREADY),
    .RDATA(m_axi_A_RDATA),
    .RLAST(m_axi_A_RLAST),
    .RID(m_axi_A_RID),
    .RUSER(m_axi_A_RUSER),
    .RRESP(m_axi_A_RRESP),
    .BVALID(m_axi_A_BVALID),
    .BREADY(m_axi_A_BREADY),
    .BRESP(m_axi_A_BRESP),
    .BID(m_axi_A_BID),
    .BUSER(m_axi_A_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(A_ARVALID),
    .I_ARREADY(A_ARREADY),
    .I_ARADDR(sext_ln49_fu_263_p1),
    .I_ARID(1'd0),
    .I_ARLEN(32'd256),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(A_RVALID),
    .I_RREADY(A_RREADY),
    .I_RDATA(A_RDATA),
    .I_RID(A_RID),
    .I_RUSER(A_RUSER),
    .I_RRESP(A_RRESP),
    .I_RLAST(A_RLAST),
    .I_AWVALID(A_AWVALID),
    .I_AWREADY(A_AWREADY),
    .I_AWADDR(A_addr_reg_408),
    .I_AWID(1'd0),
    .I_AWLEN(32'd256),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(A_WVALID),
    .I_WREADY(A_WREADY),
    .I_WDATA(A_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(64'd18446744073709551615),
    .I_BVALID(A_BVALID),
    .I_BREADY(A_BREADY),
    .I_BRESP(A_BRESP),
    .I_BID(A_BID),
    .I_BUSER(A_BUSER)
);

rtl_kernel_wizard_0_A_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
A_input_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_input_buffer_address0),
    .ce0(A_input_buffer_ce0),
    .we0(A_input_buffer_we0),
    .d0(A_input_buffer_d0),
    .q0(A_input_buffer_q0)
);

rtl_kernel_wizard_0_A_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
A_output_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_output_buffer_address0),
    .ce0(A_output_buffer_ce0),
    .we0(A_output_buffer_we0),
    .d0(A_output_buffer_d0),
    .q0(A_output_buffer_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state72) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state71)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state72)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state72);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state71)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state76) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state75)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state76))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state76);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state75)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state79) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state79)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state79);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        i_reg_219 <= 13'd0;
    end else if (((icmp_ln52_fu_326_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_reg_219 <= add_ln52_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond64_reg_420 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_index4_reg_186 <= empty_22_reg_415;
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        loop_index4_reg_186 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_350_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        loop_index_reg_230 <= empty_30_fu_344_p2;
    end else if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
        loop_index_reg_230 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond64_reg_420_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        shiftreg9_reg_198 <= {{ap_phi_mux_empty_26_phi_fu_213_p4[511:32]}};
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        shiftreg9_reg_198 <= 480'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_reg_462_pp2_iter1_reg == 1'd0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        shiftreg_reg_241 <= empty_34_fu_396_p3;
    end else if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
        shiftreg_reg_241 <= 480'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op246_read_state73 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_addr_read_reg_428 <= A_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_addr_reg_408 <= sext_ln49_fu_263_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (exitcond2_reg_462 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        A_output_buffer_load_reg_476 <= A_output_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_22_reg_415 <= empty_22_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond64_fu_279_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_25_reg_424 <= empty_25_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_25_reg_424_pp0_iter1_reg <= empty_25_reg_424;
        exitcond64_reg_420 <= exitcond64_fu_279_p2;
        exitcond64_reg_420_pp0_iter1_reg <= exitcond64_reg_420;
        loop_index4_reg_186_pp0_iter1_reg <= loop_index4_reg_186;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_350_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        empty_33_reg_471 <= empty_33_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        empty_33_reg_471_pp2_iter1_reg <= empty_33_reg_471;
        exitcond2_reg_462 <= exitcond2_fu_350_p2;
        exitcond2_reg_462_pp2_iter1_reg <= exitcond2_reg_462;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_326_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_cast_reg_447[12 : 0] <= i_cast_fu_332_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln52_reg_443 <= icmp_ln52_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_403 <= {{axi00_ptr0[63:6]}};
    end
end

always @ (*) begin
    if (((1'b1 == A_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        A_ARVALID = 1'b1;
    end else begin
        A_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
        A_AWVALID = 1'b1;
    end else begin
        A_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == A_BVALID) & (1'b1 == ap_CS_fsm_state149))) begin
        A_BREADY = 1'b1;
    end else begin
        A_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op246_read_state73 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_RREADY = 1'b1;
    end else begin
        A_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((empty_33_reg_471_pp2_iter1_reg == 1'd1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        A_WVALID = 1'b1;
    end else begin
        A_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_blk_n_AR = m_axi_A_ARREADY;
    end else begin
        A_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        A_blk_n_AW = m_axi_A_AWREADY;
    end else begin
        A_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state149)) begin
        A_blk_n_B = m_axi_A_BVALID;
    end else begin
        A_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((empty_25_reg_424 == 1'd1) & (exitcond64_reg_420 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_blk_n_R = m_axi_A_RVALID;
    end else begin
        A_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((empty_33_reg_471_pp2_iter1_reg == 1'd1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        A_blk_n_W = m_axi_A_WREADY;
    end else begin
        A_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        A_input_buffer_address0 = i_cast_fu_332_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        A_input_buffer_address0 = loop_index4_cast2_fu_300_p1;
    end else begin
        A_input_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        A_input_buffer_ce0 = 1'b1;
    end else begin
        A_input_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond64_reg_420_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_input_buffer_we0 = 1'b1;
    end else begin
        A_input_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        A_output_buffer_address0 = loop_index_cast3_fu_356_p1;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        A_output_buffer_address0 = i_cast_reg_447;
    end else begin
        A_output_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        A_output_buffer_ce0 = 1'b1;
    end else begin
        A_output_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln52_reg_443 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        A_output_buffer_we0 = 1'b1;
    end else begin
        A_output_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond64_fu_279_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state72 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state72 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln52_fu_326_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state76 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state76 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond2_fu_350_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state79 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state79 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == A_BVALID) & (1'b1 == ap_CS_fsm_state149))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond64_reg_420_pp0_iter1_reg == 1'd0)) begin
        if ((empty_25_reg_424_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_empty_26_phi_fu_213_p4 = shiftreg9_cast_fu_295_p1;
        end else if ((empty_25_reg_424_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_empty_26_phi_fu_213_p4 = A_addr_read_reg_428;
        end else begin
            ap_phi_mux_empty_26_phi_fu_213_p4 = ap_phi_reg_pp0_iter2_empty_26_reg_210;
        end
    end else begin
        ap_phi_mux_empty_26_phi_fu_213_p4 = ap_phi_reg_pp0_iter2_empty_26_reg_210;
    end
end

always @ (*) begin
    if (((exitcond64_reg_420 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_loop_index4_phi_fu_190_p4 = empty_22_reg_415;
    end else begin
        ap_phi_mux_loop_index4_phi_fu_190_p4 = loop_index4_reg_186;
    end
end

always @ (*) begin
    if (((1'b1 == A_BVALID) & (1'b1 == ap_CS_fsm_state149))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == A_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond64_fu_279_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((exitcond64_fu_279_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((icmp_ln52_fu_326_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((icmp_ln52_fu_326_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state78 : begin
            if (((1'b1 == A_AWREADY) & (1'b1 == ap_CS_fsm_state78))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_enable_reg_pp2_iter1 == 1'b0) & (exitcond2_fu_350_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)) & ~((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((ap_enable_reg_pp2_iter1 == 1'b0) & (exitcond2_fu_350_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)) | ((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state82;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            ap_NS_fsm = ap_ST_fsm_state145;
        end
        ap_ST_fsm_state145 : begin
            ap_NS_fsm = ap_ST_fsm_state146;
        end
        ap_ST_fsm_state146 : begin
            ap_NS_fsm = ap_ST_fsm_state147;
        end
        ap_ST_fsm_state147 : begin
            ap_NS_fsm = ap_ST_fsm_state148;
        end
        ap_ST_fsm_state148 : begin
            ap_NS_fsm = ap_ST_fsm_state149;
        end
        ap_ST_fsm_state149 : begin
            if (((1'b1 == A_BVALID) & (1'b1 == ap_CS_fsm_state149))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state149;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_WDATA = {{A_output_buffer_load_reg_476}, {shiftreg_reg_241}};

assign A_input_buffer_d0 = ap_phi_mux_empty_26_phi_fu_213_p4[31:0];

assign A_output_buffer_d0 = (A_input_buffer_q0 + 32'd1);

assign add_ln52_fu_320_p2 = (i_reg_219 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state149 = ap_CS_fsm[32'd143];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd74];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op246_read_state73 == 1'b1) & (1'b0 == A_RVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op246_read_state73 == 1'b1) & (1'b0 == A_RVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_block_state81_io));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_block_state81_io));
end

assign ap_block_state72_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state73_pp0_stage0_iter1 = ((ap_predicate_op246_read_state73 == 1'b1) & (1'b0 == A_RVALID));
end

assign ap_block_state74_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state76_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state77_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state79_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state80_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state81_io = ((1'b0 == A_WREADY) & (empty_33_reg_471_pp2_iter1_reg == 1'd1));
end

assign ap_block_state81_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_phi_reg_pp0_iter2_empty_26_reg_210 = 'bx;

always @ (*) begin
    ap_predicate_op246_read_state73 = ((empty_25_reg_424 == 1'd1) & (exitcond64_reg_420 == 1'd0));
end

assign empty_22_fu_273_p2 = (ap_phi_mux_loop_index4_phi_fu_190_p4 + 13'd1);

assign empty_24_fu_285_p1 = ap_phi_mux_loop_index4_phi_fu_190_p4[3:0];

assign empty_25_fu_289_p2 = ((empty_24_fu_285_p1 == 4'd0) ? 1'b1 : 1'b0);

assign empty_30_fu_344_p2 = (loop_index_reg_230 + 13'd1);

assign empty_32_fu_361_p1 = loop_index_reg_230[3:0];

assign empty_33_fu_365_p2 = ((empty_32_fu_361_p1 == 4'd15) ? 1'b1 : 1'b0);

assign empty_34_fu_396_p3 = ((empty_33_reg_471_pp2_iter1_reg[0:0] == 1'b1) ? 480'd0 : tmp_2_fu_389_p3);

assign exitcond2_fu_350_p2 = ((loop_index_reg_230 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond64_fu_279_p2 = ((ap_phi_mux_loop_index4_phi_fu_190_p4 == 13'd4096) ? 1'b1 : 1'b0);

assign i_cast_fu_332_p1 = i_reg_219;

assign icmp_ln52_fu_326_p2 = ((i_reg_219 == 13'd4096) ? 1'b1 : 1'b0);

assign loop_index4_cast2_fu_300_p1 = loop_index4_reg_186_pp0_iter1_reg;

assign loop_index_cast3_fu_356_p1 = loop_index_reg_230;

assign sext_ln49_fu_263_p1 = $signed(trunc_ln_reg_403);

assign shiftreg9_cast_fu_295_p1 = shiftreg9_reg_198;

assign tmp_1_fu_379_p4 = {{shiftreg_reg_241[479:32]}};

assign tmp_2_fu_389_p3 = {{A_output_buffer_load_reg_476}, {tmp_1_fu_379_p4}};

always @ (posedge ap_clk) begin
    i_cast_reg_447[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //rtl_kernel_wizard_0
