#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Mar 16 18:13:39 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib gtwizard_ultrascale_v1_7_9 cmac_usplus_v3_1_2 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 xlconstant_v1_1_7 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 axi_vip_v1_1_8)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/design_1_cmac_usplus_0_0_gt_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/design_1_cmac_usplus_0_0_gt_gtye4_common_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/design_1_cmac_usplus_0_0_gt_gtwizard_gtye4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/design_1_cmac_usplus_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/ip_0/sim/design_1_cmac_usplus_0_0_gt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_0_0_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_0_0_ultrascale_tx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_0_0_ultrascale_rx_userclk.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work cmac_usplus_v3_1_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1193/hdl/cmac_usplus_v3_1_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/design_1_cmac_usplus_0_0/example_design/design_1_cmac_usplus_0_0_axis2lbus_segmented_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/design_1_cmac_usplus_0_0/example_design/design_1_cmac_usplus_0_0_lbus2axis_segmented_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_0_0/design_1_cmac_usplus_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/ip_0/sim/design_1_cmac_usplus_1_0_gt_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/ip_0/sim/design_1_cmac_usplus_1_0_gt_gtye4_common_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/ip_0/sim/design_1_cmac_usplus_1_0_gt_gtwizard_gtye4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/ip_0/sim/design_1_cmac_usplus_1_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/ip_0/sim/design_1_cmac_usplus_1_0_gt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_1_0_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_1_0_ultrascale_tx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/cmac_usplus_v3_1_2/design_1_cmac_usplus_1_0_ultrascale_rx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/design_1_cmac_usplus_1_0/example_design/design_1_cmac_usplus_1_0_axis2lbus_segmented_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/design_1_cmac_usplus_1_0/example_design/design_1_cmac_usplus_1_0_lbus2axis_segmented_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cmac_usplus_1_0/design_1_cmac_usplus_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_dsp_send_0_0/sim/design_1_dsp_send_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_dsp_send_1_0/sim/design_1_dsp_send_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_embedded_test_ip_wra_0_0/design_1_embedded_test_ip_wra_0_0_sim_netlist.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_embedded_test_ip_wra_1_0/design_1_embedded_test_ip_wra_1_0_sim_netlist.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ila_0_0/sim/design_1_ila_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ila_1_0/sim/design_1_ila_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_1_0/sim/design_1_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_serial_pipe_0_0/sim/design_1_serial_pipe_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_serial_pipe_1_0/sim/design_1_serial_pipe_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_serial_pipe_2_0/sim/design_1_serial_pipe_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_udp_core_eval_0_0/design_1_udp_core_eval_0_0_sim_netlist.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_udp_core_eval_1_0/design_1_udp_core_eval_1_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_0/sim/design_1_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_0/sim/design_1_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_4_0/sim/design_1_util_vector_logic_4_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_9_0/sim/design_1_util_vector_logic_9_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_10_0/sim/design_1_util_vector_logic_10_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_11_0/sim/design_1_util_vector_logic_11_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_12_0/sim/design_1_util_vector_logic_12_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_13_0/sim/design_1_util_vector_logic_13_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_15_0/sim/design_1_util_vector_logic_15_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_2_0/sim/design_1_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_m00e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_m01s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_m01arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_m01rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m01awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_m01wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_m01bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_m01e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_m02s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_m02arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_48ac_m02rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_48ac_m02awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_48ac_m02wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_48ac_m02bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_48ac_m02e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_48ac_m03s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_48ac_m03arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_48ac_m03rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_48ac_m03awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_48ac_m03wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_48ac_m03bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_48ac_m03e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_rtl_kernel_wizard_0_0_0/sim/design_1_rtl_kernel_wizard_0_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_0/sim/bd_483c_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_1/sim/bd_483c_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_2/sim/bd_483c_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_3/sim/bd_483c_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_4/sim/bd_483c_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_5/sim/bd_483c_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_6/sim/bd_483c_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_7/sim/bd_483c_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_8/sim/bd_483c_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_9/sim/bd_483c_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_10/sim/bd_483c_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_11/sim/bd_483c_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_12/sim/bd_483c_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_13/sim/bd_483c_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_14/sim/bd_483c_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_15/sim/bd_483c_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_16/sim/bd_483c_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_17/sim/bd_483c_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_18/sim/bd_483c_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_19/sim/bd_483c_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_20/sim/bd_483c_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_21/sim/bd_483c_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_22/sim/bd_483c_m00e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_23/sim/bd_483c_m01s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_24/sim/bd_483c_m01arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_25/sim/bd_483c_m01rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_26/sim/bd_483c_m01awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_27/sim/bd_483c_m01wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_28/sim/bd_483c_m01bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/ip/ip_29/sim/bd_483c_m01e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/bd_0/sim/bd_483c.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_1_1/sim/design_1_smartconnect_1_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
